/*
Farcaster Hub API

Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 

API version: 2.21.0
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hub

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FetchUserOnChainEvents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchUserOnChainEvents200Response{}

// FetchUserOnChainEvents200Response struct for FetchUserOnChainEvents200Response
type FetchUserOnChainEvents200Response struct {
	Events []OnChainEvent `json:"events"`
}

type _FetchUserOnChainEvents200Response FetchUserOnChainEvents200Response

// NewFetchUserOnChainEvents200Response instantiates a new FetchUserOnChainEvents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchUserOnChainEvents200Response(events []OnChainEvent) *FetchUserOnChainEvents200Response {
	this := FetchUserOnChainEvents200Response{}
	this.Events = events
	return &this
}

// NewFetchUserOnChainEvents200ResponseWithDefaults instantiates a new FetchUserOnChainEvents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchUserOnChainEvents200ResponseWithDefaults() *FetchUserOnChainEvents200Response {
	this := FetchUserOnChainEvents200Response{}
	return &this
}

// GetEvents returns the Events field value
func (o *FetchUserOnChainEvents200Response) GetEvents() []OnChainEvent {
	if o == nil {
		var ret []OnChainEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *FetchUserOnChainEvents200Response) GetEventsOk() ([]OnChainEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *FetchUserOnChainEvents200Response) SetEvents(v []OnChainEvent) {
	o.Events = v
}

func (o FetchUserOnChainEvents200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchUserOnChainEvents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *FetchUserOnChainEvents200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFetchUserOnChainEvents200Response := _FetchUserOnChainEvents200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFetchUserOnChainEvents200Response)

	if err != nil {
		return err
	}

	*o = FetchUserOnChainEvents200Response(varFetchUserOnChainEvents200Response)

	return err
}

type NullableFetchUserOnChainEvents200Response struct {
	value *FetchUserOnChainEvents200Response
	isSet bool
}

func (v NullableFetchUserOnChainEvents200Response) Get() *FetchUserOnChainEvents200Response {
	return v.value
}

func (v *NullableFetchUserOnChainEvents200Response) Set(val *FetchUserOnChainEvents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchUserOnChainEvents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchUserOnChainEvents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchUserOnChainEvents200Response(val *FetchUserOnChainEvents200Response) *NullableFetchUserOnChainEvents200Response {
	return &NullableFetchUserOnChainEvents200Response{value: val, isSet: true}
}

func (v NullableFetchUserOnChainEvents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchUserOnChainEvents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


