/*
Farcaster Hub API

Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details.

API version: 2.21.0
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hub

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FetchUserOnChainSignersEvents200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchUserOnChainSignersEvents200ResponseOneOf{}

// FetchUserOnChainSignersEvents200ResponseOneOf struct for FetchUserOnChainSignersEvents200ResponseOneOf
type FetchUserOnChainSignersEvents200ResponseOneOf struct {
	Events []OnChainEventSigner `json:"events"`
}

type _FetchUserOnChainSignersEvents200ResponseOneOf FetchUserOnChainSignersEvents200ResponseOneOf

// NewFetchUserOnChainSignersEvents200ResponseOneOf instantiates a new FetchUserOnChainSignersEvents200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchUserOnChainSignersEvents200ResponseOneOf(events []OnChainEventSigner) *FetchUserOnChainSignersEvents200ResponseOneOf {
	this := FetchUserOnChainSignersEvents200ResponseOneOf{}
	this.Events = events
	return &this
}

// NewFetchUserOnChainSignersEvents200ResponseOneOfWithDefaults instantiates a new FetchUserOnChainSignersEvents200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchUserOnChainSignersEvents200ResponseOneOfWithDefaults() *FetchUserOnChainSignersEvents200ResponseOneOf {
	this := FetchUserOnChainSignersEvents200ResponseOneOf{}
	return &this
}

// GetEvents returns the Events field value
func (o *FetchUserOnChainSignersEvents200ResponseOneOf) GetEvents() []OnChainEventSigner {
	if o == nil {
		var ret []OnChainEventSigner
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *FetchUserOnChainSignersEvents200ResponseOneOf) GetEventsOk() ([]OnChainEventSigner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *FetchUserOnChainSignersEvents200ResponseOneOf) SetEvents(v []OnChainEventSigner) {
	o.Events = v
}

func (o FetchUserOnChainSignersEvents200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchUserOnChainSignersEvents200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *FetchUserOnChainSignersEvents200ResponseOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varFetchUserOnChainSignersEvents200ResponseOneOf := _FetchUserOnChainSignersEvents200ResponseOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFetchUserOnChainSignersEvents200ResponseOneOf)

	if err != nil {
		return err
	}

	*o = FetchUserOnChainSignersEvents200ResponseOneOf(varFetchUserOnChainSignersEvents200ResponseOneOf)

	return err
}

type NullableFetchUserOnChainSignersEvents200ResponseOneOf struct {
	value *FetchUserOnChainSignersEvents200ResponseOneOf
	isSet bool
}

func (v NullableFetchUserOnChainSignersEvents200ResponseOneOf) Get() *FetchUserOnChainSignersEvents200ResponseOneOf {
	return v.value
}

func (v *NullableFetchUserOnChainSignersEvents200ResponseOneOf) Set(val *FetchUserOnChainSignersEvents200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchUserOnChainSignersEvents200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchUserOnChainSignersEvents200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchUserOnChainSignersEvents200ResponseOneOf(val *FetchUserOnChainSignersEvents200ResponseOneOf) *NullableFetchUserOnChainSignersEvents200ResponseOneOf {
	return &NullableFetchUserOnChainSignersEvents200ResponseOneOf{value: val, isSet: true}
}

func (v NullableFetchUserOnChainSignersEvents200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchUserOnChainSignersEvents200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
