/*
Farcaster API V2

The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 

API version: 2.33.1
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OgObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OgObject{}

// OgObject struct for OgObject
type OgObject struct {
	Favicon *string `json:"favicon,omitempty"`
	ModifiedTime *string `json:"modifiedTime,omitempty"`
	OgArticleAuthor *string `json:"ogArticleAuthor,omitempty"`
	OgArticleExpirationTime *string `json:"ogArticleExpirationTime,omitempty"`
	OgArticleModifiedTime *string `json:"ogArticleModifiedTime,omitempty"`
	OgArticlePublishedTime *string `json:"ogArticlePublishedTime,omitempty"`
	OgArticlePublisher *string `json:"ogArticlePublisher,omitempty"`
	OgArticleSection *string `json:"ogArticleSection,omitempty"`
	OgArticleTag *string `json:"ogArticleTag,omitempty"`
	OgAudio *string `json:"ogAudio,omitempty"`
	OgAudioSecureURL *string `json:"ogAudioSecureURL,omitempty"`
	OgAudioType *string `json:"ogAudioType,omitempty"`
	OgAudioURL *string `json:"ogAudioURL,omitempty"`
	OgAvailability *string `json:"ogAvailability,omitempty"`
	OgDate *string `json:"ogDate,omitempty"`
	OgDescription *string `json:"ogDescription,omitempty"`
	OgDeterminer *string `json:"ogDeterminer,omitempty"`
	OgEpisode *string `json:"ogEpisode,omitempty"`
	OgImage []ImageObject `json:"ogImage,omitempty"`
	OgLocale *string `json:"ogLocale,omitempty"`
	OgLocaleAlternate *string `json:"ogLocaleAlternate,omitempty"`
	OgLogo *string `json:"ogLogo,omitempty"`
	OgMovie *string `json:"ogMovie,omitempty"`
	OgPriceAmount *string `json:"ogPriceAmount,omitempty"`
	OgPriceCurrency *string `json:"ogPriceCurrency,omitempty"`
	OgProductAvailability *string `json:"ogProductAvailability,omitempty"`
	OgProductCondition *string `json:"ogProductCondition,omitempty"`
	OgProductPriceAmount *string `json:"ogProductPriceAmount,omitempty"`
	OgProductPriceCurrency *string `json:"ogProductPriceCurrency,omitempty"`
	OgProductRetailerItemId *string `json:"ogProductRetailerItemId,omitempty"`
	OgSiteName *string `json:"ogSiteName,omitempty"`
	OgTitle *string `json:"ogTitle,omitempty"`
	OgType *string `json:"ogType,omitempty"`
	OgUrl *string `json:"ogUrl,omitempty"`
	OgVideo []VideoObject `json:"ogVideo,omitempty"`
	OgVideoActor *string `json:"ogVideoActor,omitempty"`
	OgVideoActorId *string `json:"ogVideoActorId,omitempty"`
	OgVideoActorRole *string `json:"ogVideoActorRole,omitempty"`
	OgVideoDirector *string `json:"ogVideoDirector,omitempty"`
	OgVideoDuration *string `json:"ogVideoDuration,omitempty"`
	OgVideoOther *string `json:"ogVideoOther,omitempty"`
	OgVideoReleaseDate *string `json:"ogVideoReleaseDate,omitempty"`
	OgVideoSecureURL *string `json:"ogVideoSecureURL,omitempty"`
	OgVideoSeries *string `json:"ogVideoSeries,omitempty"`
	OgVideoTag *string `json:"ogVideoTag,omitempty"`
	OgVideoTvShow *string `json:"ogVideoTvShow,omitempty"`
	OgVideoWriter *string `json:"ogVideoWriter,omitempty"`
	OgWebsite *string `json:"ogWebsite,omitempty"`
	UpdatedTime *string `json:"updatedTime,omitempty"`
}

// NewOgObject instantiates a new OgObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOgObject() *OgObject {
	this := OgObject{}
	return &this
}

// NewOgObjectWithDefaults instantiates a new OgObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOgObjectWithDefaults() *OgObject {
	this := OgObject{}
	return &this
}

// GetFavicon returns the Favicon field value if set, zero value otherwise.
func (o *OgObject) GetFavicon() string {
	if o == nil || IsNil(o.Favicon) {
		var ret string
		return ret
	}
	return *o.Favicon
}

// GetFaviconOk returns a tuple with the Favicon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetFaviconOk() (*string, bool) {
	if o == nil || IsNil(o.Favicon) {
		return nil, false
	}
	return o.Favicon, true
}

// HasFavicon returns a boolean if a field has been set.
func (o *OgObject) HasFavicon() bool {
	if o != nil && !IsNil(o.Favicon) {
		return true
	}

	return false
}

// SetFavicon gets a reference to the given string and assigns it to the Favicon field.
func (o *OgObject) SetFavicon(v string) {
	o.Favicon = &v
}

// GetModifiedTime returns the ModifiedTime field value if set, zero value otherwise.
func (o *OgObject) GetModifiedTime() string {
	if o == nil || IsNil(o.ModifiedTime) {
		var ret string
		return ret
	}
	return *o.ModifiedTime
}

// GetModifiedTimeOk returns a tuple with the ModifiedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetModifiedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ModifiedTime) {
		return nil, false
	}
	return o.ModifiedTime, true
}

// HasModifiedTime returns a boolean if a field has been set.
func (o *OgObject) HasModifiedTime() bool {
	if o != nil && !IsNil(o.ModifiedTime) {
		return true
	}

	return false
}

// SetModifiedTime gets a reference to the given string and assigns it to the ModifiedTime field.
func (o *OgObject) SetModifiedTime(v string) {
	o.ModifiedTime = &v
}

// GetOgArticleAuthor returns the OgArticleAuthor field value if set, zero value otherwise.
func (o *OgObject) GetOgArticleAuthor() string {
	if o == nil || IsNil(o.OgArticleAuthor) {
		var ret string
		return ret
	}
	return *o.OgArticleAuthor
}

// GetOgArticleAuthorOk returns a tuple with the OgArticleAuthor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticleAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticleAuthor) {
		return nil, false
	}
	return o.OgArticleAuthor, true
}

// HasOgArticleAuthor returns a boolean if a field has been set.
func (o *OgObject) HasOgArticleAuthor() bool {
	if o != nil && !IsNil(o.OgArticleAuthor) {
		return true
	}

	return false
}

// SetOgArticleAuthor gets a reference to the given string and assigns it to the OgArticleAuthor field.
func (o *OgObject) SetOgArticleAuthor(v string) {
	o.OgArticleAuthor = &v
}

// GetOgArticleExpirationTime returns the OgArticleExpirationTime field value if set, zero value otherwise.
func (o *OgObject) GetOgArticleExpirationTime() string {
	if o == nil || IsNil(o.OgArticleExpirationTime) {
		var ret string
		return ret
	}
	return *o.OgArticleExpirationTime
}

// GetOgArticleExpirationTimeOk returns a tuple with the OgArticleExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticleExpirationTimeOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticleExpirationTime) {
		return nil, false
	}
	return o.OgArticleExpirationTime, true
}

// HasOgArticleExpirationTime returns a boolean if a field has been set.
func (o *OgObject) HasOgArticleExpirationTime() bool {
	if o != nil && !IsNil(o.OgArticleExpirationTime) {
		return true
	}

	return false
}

// SetOgArticleExpirationTime gets a reference to the given string and assigns it to the OgArticleExpirationTime field.
func (o *OgObject) SetOgArticleExpirationTime(v string) {
	o.OgArticleExpirationTime = &v
}

// GetOgArticleModifiedTime returns the OgArticleModifiedTime field value if set, zero value otherwise.
func (o *OgObject) GetOgArticleModifiedTime() string {
	if o == nil || IsNil(o.OgArticleModifiedTime) {
		var ret string
		return ret
	}
	return *o.OgArticleModifiedTime
}

// GetOgArticleModifiedTimeOk returns a tuple with the OgArticleModifiedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticleModifiedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticleModifiedTime) {
		return nil, false
	}
	return o.OgArticleModifiedTime, true
}

// HasOgArticleModifiedTime returns a boolean if a field has been set.
func (o *OgObject) HasOgArticleModifiedTime() bool {
	if o != nil && !IsNil(o.OgArticleModifiedTime) {
		return true
	}

	return false
}

// SetOgArticleModifiedTime gets a reference to the given string and assigns it to the OgArticleModifiedTime field.
func (o *OgObject) SetOgArticleModifiedTime(v string) {
	o.OgArticleModifiedTime = &v
}

// GetOgArticlePublishedTime returns the OgArticlePublishedTime field value if set, zero value otherwise.
func (o *OgObject) GetOgArticlePublishedTime() string {
	if o == nil || IsNil(o.OgArticlePublishedTime) {
		var ret string
		return ret
	}
	return *o.OgArticlePublishedTime
}

// GetOgArticlePublishedTimeOk returns a tuple with the OgArticlePublishedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticlePublishedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticlePublishedTime) {
		return nil, false
	}
	return o.OgArticlePublishedTime, true
}

// HasOgArticlePublishedTime returns a boolean if a field has been set.
func (o *OgObject) HasOgArticlePublishedTime() bool {
	if o != nil && !IsNil(o.OgArticlePublishedTime) {
		return true
	}

	return false
}

// SetOgArticlePublishedTime gets a reference to the given string and assigns it to the OgArticlePublishedTime field.
func (o *OgObject) SetOgArticlePublishedTime(v string) {
	o.OgArticlePublishedTime = &v
}

// GetOgArticlePublisher returns the OgArticlePublisher field value if set, zero value otherwise.
func (o *OgObject) GetOgArticlePublisher() string {
	if o == nil || IsNil(o.OgArticlePublisher) {
		var ret string
		return ret
	}
	return *o.OgArticlePublisher
}

// GetOgArticlePublisherOk returns a tuple with the OgArticlePublisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticlePublisherOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticlePublisher) {
		return nil, false
	}
	return o.OgArticlePublisher, true
}

// HasOgArticlePublisher returns a boolean if a field has been set.
func (o *OgObject) HasOgArticlePublisher() bool {
	if o != nil && !IsNil(o.OgArticlePublisher) {
		return true
	}

	return false
}

// SetOgArticlePublisher gets a reference to the given string and assigns it to the OgArticlePublisher field.
func (o *OgObject) SetOgArticlePublisher(v string) {
	o.OgArticlePublisher = &v
}

// GetOgArticleSection returns the OgArticleSection field value if set, zero value otherwise.
func (o *OgObject) GetOgArticleSection() string {
	if o == nil || IsNil(o.OgArticleSection) {
		var ret string
		return ret
	}
	return *o.OgArticleSection
}

// GetOgArticleSectionOk returns a tuple with the OgArticleSection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticleSectionOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticleSection) {
		return nil, false
	}
	return o.OgArticleSection, true
}

// HasOgArticleSection returns a boolean if a field has been set.
func (o *OgObject) HasOgArticleSection() bool {
	if o != nil && !IsNil(o.OgArticleSection) {
		return true
	}

	return false
}

// SetOgArticleSection gets a reference to the given string and assigns it to the OgArticleSection field.
func (o *OgObject) SetOgArticleSection(v string) {
	o.OgArticleSection = &v
}

// GetOgArticleTag returns the OgArticleTag field value if set, zero value otherwise.
func (o *OgObject) GetOgArticleTag() string {
	if o == nil || IsNil(o.OgArticleTag) {
		var ret string
		return ret
	}
	return *o.OgArticleTag
}

// GetOgArticleTagOk returns a tuple with the OgArticleTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgArticleTagOk() (*string, bool) {
	if o == nil || IsNil(o.OgArticleTag) {
		return nil, false
	}
	return o.OgArticleTag, true
}

// HasOgArticleTag returns a boolean if a field has been set.
func (o *OgObject) HasOgArticleTag() bool {
	if o != nil && !IsNil(o.OgArticleTag) {
		return true
	}

	return false
}

// SetOgArticleTag gets a reference to the given string and assigns it to the OgArticleTag field.
func (o *OgObject) SetOgArticleTag(v string) {
	o.OgArticleTag = &v
}

// GetOgAudio returns the OgAudio field value if set, zero value otherwise.
func (o *OgObject) GetOgAudio() string {
	if o == nil || IsNil(o.OgAudio) {
		var ret string
		return ret
	}
	return *o.OgAudio
}

// GetOgAudioOk returns a tuple with the OgAudio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgAudioOk() (*string, bool) {
	if o == nil || IsNil(o.OgAudio) {
		return nil, false
	}
	return o.OgAudio, true
}

// HasOgAudio returns a boolean if a field has been set.
func (o *OgObject) HasOgAudio() bool {
	if o != nil && !IsNil(o.OgAudio) {
		return true
	}

	return false
}

// SetOgAudio gets a reference to the given string and assigns it to the OgAudio field.
func (o *OgObject) SetOgAudio(v string) {
	o.OgAudio = &v
}

// GetOgAudioSecureURL returns the OgAudioSecureURL field value if set, zero value otherwise.
func (o *OgObject) GetOgAudioSecureURL() string {
	if o == nil || IsNil(o.OgAudioSecureURL) {
		var ret string
		return ret
	}
	return *o.OgAudioSecureURL
}

// GetOgAudioSecureURLOk returns a tuple with the OgAudioSecureURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgAudioSecureURLOk() (*string, bool) {
	if o == nil || IsNil(o.OgAudioSecureURL) {
		return nil, false
	}
	return o.OgAudioSecureURL, true
}

// HasOgAudioSecureURL returns a boolean if a field has been set.
func (o *OgObject) HasOgAudioSecureURL() bool {
	if o != nil && !IsNil(o.OgAudioSecureURL) {
		return true
	}

	return false
}

// SetOgAudioSecureURL gets a reference to the given string and assigns it to the OgAudioSecureURL field.
func (o *OgObject) SetOgAudioSecureURL(v string) {
	o.OgAudioSecureURL = &v
}

// GetOgAudioType returns the OgAudioType field value if set, zero value otherwise.
func (o *OgObject) GetOgAudioType() string {
	if o == nil || IsNil(o.OgAudioType) {
		var ret string
		return ret
	}
	return *o.OgAudioType
}

// GetOgAudioTypeOk returns a tuple with the OgAudioType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgAudioTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OgAudioType) {
		return nil, false
	}
	return o.OgAudioType, true
}

// HasOgAudioType returns a boolean if a field has been set.
func (o *OgObject) HasOgAudioType() bool {
	if o != nil && !IsNil(o.OgAudioType) {
		return true
	}

	return false
}

// SetOgAudioType gets a reference to the given string and assigns it to the OgAudioType field.
func (o *OgObject) SetOgAudioType(v string) {
	o.OgAudioType = &v
}

// GetOgAudioURL returns the OgAudioURL field value if set, zero value otherwise.
func (o *OgObject) GetOgAudioURL() string {
	if o == nil || IsNil(o.OgAudioURL) {
		var ret string
		return ret
	}
	return *o.OgAudioURL
}

// GetOgAudioURLOk returns a tuple with the OgAudioURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgAudioURLOk() (*string, bool) {
	if o == nil || IsNil(o.OgAudioURL) {
		return nil, false
	}
	return o.OgAudioURL, true
}

// HasOgAudioURL returns a boolean if a field has been set.
func (o *OgObject) HasOgAudioURL() bool {
	if o != nil && !IsNil(o.OgAudioURL) {
		return true
	}

	return false
}

// SetOgAudioURL gets a reference to the given string and assigns it to the OgAudioURL field.
func (o *OgObject) SetOgAudioURL(v string) {
	o.OgAudioURL = &v
}

// GetOgAvailability returns the OgAvailability field value if set, zero value otherwise.
func (o *OgObject) GetOgAvailability() string {
	if o == nil || IsNil(o.OgAvailability) {
		var ret string
		return ret
	}
	return *o.OgAvailability
}

// GetOgAvailabilityOk returns a tuple with the OgAvailability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgAvailabilityOk() (*string, bool) {
	if o == nil || IsNil(o.OgAvailability) {
		return nil, false
	}
	return o.OgAvailability, true
}

// HasOgAvailability returns a boolean if a field has been set.
func (o *OgObject) HasOgAvailability() bool {
	if o != nil && !IsNil(o.OgAvailability) {
		return true
	}

	return false
}

// SetOgAvailability gets a reference to the given string and assigns it to the OgAvailability field.
func (o *OgObject) SetOgAvailability(v string) {
	o.OgAvailability = &v
}

// GetOgDate returns the OgDate field value if set, zero value otherwise.
func (o *OgObject) GetOgDate() string {
	if o == nil || IsNil(o.OgDate) {
		var ret string
		return ret
	}
	return *o.OgDate
}

// GetOgDateOk returns a tuple with the OgDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgDateOk() (*string, bool) {
	if o == nil || IsNil(o.OgDate) {
		return nil, false
	}
	return o.OgDate, true
}

// HasOgDate returns a boolean if a field has been set.
func (o *OgObject) HasOgDate() bool {
	if o != nil && !IsNil(o.OgDate) {
		return true
	}

	return false
}

// SetOgDate gets a reference to the given string and assigns it to the OgDate field.
func (o *OgObject) SetOgDate(v string) {
	o.OgDate = &v
}

// GetOgDescription returns the OgDescription field value if set, zero value otherwise.
func (o *OgObject) GetOgDescription() string {
	if o == nil || IsNil(o.OgDescription) {
		var ret string
		return ret
	}
	return *o.OgDescription
}

// GetOgDescriptionOk returns a tuple with the OgDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.OgDescription) {
		return nil, false
	}
	return o.OgDescription, true
}

// HasOgDescription returns a boolean if a field has been set.
func (o *OgObject) HasOgDescription() bool {
	if o != nil && !IsNil(o.OgDescription) {
		return true
	}

	return false
}

// SetOgDescription gets a reference to the given string and assigns it to the OgDescription field.
func (o *OgObject) SetOgDescription(v string) {
	o.OgDescription = &v
}

// GetOgDeterminer returns the OgDeterminer field value if set, zero value otherwise.
func (o *OgObject) GetOgDeterminer() string {
	if o == nil || IsNil(o.OgDeterminer) {
		var ret string
		return ret
	}
	return *o.OgDeterminer
}

// GetOgDeterminerOk returns a tuple with the OgDeterminer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgDeterminerOk() (*string, bool) {
	if o == nil || IsNil(o.OgDeterminer) {
		return nil, false
	}
	return o.OgDeterminer, true
}

// HasOgDeterminer returns a boolean if a field has been set.
func (o *OgObject) HasOgDeterminer() bool {
	if o != nil && !IsNil(o.OgDeterminer) {
		return true
	}

	return false
}

// SetOgDeterminer gets a reference to the given string and assigns it to the OgDeterminer field.
func (o *OgObject) SetOgDeterminer(v string) {
	o.OgDeterminer = &v
}

// GetOgEpisode returns the OgEpisode field value if set, zero value otherwise.
func (o *OgObject) GetOgEpisode() string {
	if o == nil || IsNil(o.OgEpisode) {
		var ret string
		return ret
	}
	return *o.OgEpisode
}

// GetOgEpisodeOk returns a tuple with the OgEpisode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgEpisodeOk() (*string, bool) {
	if o == nil || IsNil(o.OgEpisode) {
		return nil, false
	}
	return o.OgEpisode, true
}

// HasOgEpisode returns a boolean if a field has been set.
func (o *OgObject) HasOgEpisode() bool {
	if o != nil && !IsNil(o.OgEpisode) {
		return true
	}

	return false
}

// SetOgEpisode gets a reference to the given string and assigns it to the OgEpisode field.
func (o *OgObject) SetOgEpisode(v string) {
	o.OgEpisode = &v
}

// GetOgImage returns the OgImage field value if set, zero value otherwise.
func (o *OgObject) GetOgImage() []ImageObject {
	if o == nil || IsNil(o.OgImage) {
		var ret []ImageObject
		return ret
	}
	return o.OgImage
}

// GetOgImageOk returns a tuple with the OgImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgImageOk() ([]ImageObject, bool) {
	if o == nil || IsNil(o.OgImage) {
		return nil, false
	}
	return o.OgImage, true
}

// HasOgImage returns a boolean if a field has been set.
func (o *OgObject) HasOgImage() bool {
	if o != nil && !IsNil(o.OgImage) {
		return true
	}

	return false
}

// SetOgImage gets a reference to the given []ImageObject and assigns it to the OgImage field.
func (o *OgObject) SetOgImage(v []ImageObject) {
	o.OgImage = v
}

// GetOgLocale returns the OgLocale field value if set, zero value otherwise.
func (o *OgObject) GetOgLocale() string {
	if o == nil || IsNil(o.OgLocale) {
		var ret string
		return ret
	}
	return *o.OgLocale
}

// GetOgLocaleOk returns a tuple with the OgLocale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.OgLocale) {
		return nil, false
	}
	return o.OgLocale, true
}

// HasOgLocale returns a boolean if a field has been set.
func (o *OgObject) HasOgLocale() bool {
	if o != nil && !IsNil(o.OgLocale) {
		return true
	}

	return false
}

// SetOgLocale gets a reference to the given string and assigns it to the OgLocale field.
func (o *OgObject) SetOgLocale(v string) {
	o.OgLocale = &v
}

// GetOgLocaleAlternate returns the OgLocaleAlternate field value if set, zero value otherwise.
func (o *OgObject) GetOgLocaleAlternate() string {
	if o == nil || IsNil(o.OgLocaleAlternate) {
		var ret string
		return ret
	}
	return *o.OgLocaleAlternate
}

// GetOgLocaleAlternateOk returns a tuple with the OgLocaleAlternate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgLocaleAlternateOk() (*string, bool) {
	if o == nil || IsNil(o.OgLocaleAlternate) {
		return nil, false
	}
	return o.OgLocaleAlternate, true
}

// HasOgLocaleAlternate returns a boolean if a field has been set.
func (o *OgObject) HasOgLocaleAlternate() bool {
	if o != nil && !IsNil(o.OgLocaleAlternate) {
		return true
	}

	return false
}

// SetOgLocaleAlternate gets a reference to the given string and assigns it to the OgLocaleAlternate field.
func (o *OgObject) SetOgLocaleAlternate(v string) {
	o.OgLocaleAlternate = &v
}

// GetOgLogo returns the OgLogo field value if set, zero value otherwise.
func (o *OgObject) GetOgLogo() string {
	if o == nil || IsNil(o.OgLogo) {
		var ret string
		return ret
	}
	return *o.OgLogo
}

// GetOgLogoOk returns a tuple with the OgLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgLogoOk() (*string, bool) {
	if o == nil || IsNil(o.OgLogo) {
		return nil, false
	}
	return o.OgLogo, true
}

// HasOgLogo returns a boolean if a field has been set.
func (o *OgObject) HasOgLogo() bool {
	if o != nil && !IsNil(o.OgLogo) {
		return true
	}

	return false
}

// SetOgLogo gets a reference to the given string and assigns it to the OgLogo field.
func (o *OgObject) SetOgLogo(v string) {
	o.OgLogo = &v
}

// GetOgMovie returns the OgMovie field value if set, zero value otherwise.
func (o *OgObject) GetOgMovie() string {
	if o == nil || IsNil(o.OgMovie) {
		var ret string
		return ret
	}
	return *o.OgMovie
}

// GetOgMovieOk returns a tuple with the OgMovie field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgMovieOk() (*string, bool) {
	if o == nil || IsNil(o.OgMovie) {
		return nil, false
	}
	return o.OgMovie, true
}

// HasOgMovie returns a boolean if a field has been set.
func (o *OgObject) HasOgMovie() bool {
	if o != nil && !IsNil(o.OgMovie) {
		return true
	}

	return false
}

// SetOgMovie gets a reference to the given string and assigns it to the OgMovie field.
func (o *OgObject) SetOgMovie(v string) {
	o.OgMovie = &v
}

// GetOgPriceAmount returns the OgPriceAmount field value if set, zero value otherwise.
func (o *OgObject) GetOgPriceAmount() string {
	if o == nil || IsNil(o.OgPriceAmount) {
		var ret string
		return ret
	}
	return *o.OgPriceAmount
}

// GetOgPriceAmountOk returns a tuple with the OgPriceAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgPriceAmountOk() (*string, bool) {
	if o == nil || IsNil(o.OgPriceAmount) {
		return nil, false
	}
	return o.OgPriceAmount, true
}

// HasOgPriceAmount returns a boolean if a field has been set.
func (o *OgObject) HasOgPriceAmount() bool {
	if o != nil && !IsNil(o.OgPriceAmount) {
		return true
	}

	return false
}

// SetOgPriceAmount gets a reference to the given string and assigns it to the OgPriceAmount field.
func (o *OgObject) SetOgPriceAmount(v string) {
	o.OgPriceAmount = &v
}

// GetOgPriceCurrency returns the OgPriceCurrency field value if set, zero value otherwise.
func (o *OgObject) GetOgPriceCurrency() string {
	if o == nil || IsNil(o.OgPriceCurrency) {
		var ret string
		return ret
	}
	return *o.OgPriceCurrency
}

// GetOgPriceCurrencyOk returns a tuple with the OgPriceCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgPriceCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.OgPriceCurrency) {
		return nil, false
	}
	return o.OgPriceCurrency, true
}

// HasOgPriceCurrency returns a boolean if a field has been set.
func (o *OgObject) HasOgPriceCurrency() bool {
	if o != nil && !IsNil(o.OgPriceCurrency) {
		return true
	}

	return false
}

// SetOgPriceCurrency gets a reference to the given string and assigns it to the OgPriceCurrency field.
func (o *OgObject) SetOgPriceCurrency(v string) {
	o.OgPriceCurrency = &v
}

// GetOgProductAvailability returns the OgProductAvailability field value if set, zero value otherwise.
func (o *OgObject) GetOgProductAvailability() string {
	if o == nil || IsNil(o.OgProductAvailability) {
		var ret string
		return ret
	}
	return *o.OgProductAvailability
}

// GetOgProductAvailabilityOk returns a tuple with the OgProductAvailability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgProductAvailabilityOk() (*string, bool) {
	if o == nil || IsNil(o.OgProductAvailability) {
		return nil, false
	}
	return o.OgProductAvailability, true
}

// HasOgProductAvailability returns a boolean if a field has been set.
func (o *OgObject) HasOgProductAvailability() bool {
	if o != nil && !IsNil(o.OgProductAvailability) {
		return true
	}

	return false
}

// SetOgProductAvailability gets a reference to the given string and assigns it to the OgProductAvailability field.
func (o *OgObject) SetOgProductAvailability(v string) {
	o.OgProductAvailability = &v
}

// GetOgProductCondition returns the OgProductCondition field value if set, zero value otherwise.
func (o *OgObject) GetOgProductCondition() string {
	if o == nil || IsNil(o.OgProductCondition) {
		var ret string
		return ret
	}
	return *o.OgProductCondition
}

// GetOgProductConditionOk returns a tuple with the OgProductCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgProductConditionOk() (*string, bool) {
	if o == nil || IsNil(o.OgProductCondition) {
		return nil, false
	}
	return o.OgProductCondition, true
}

// HasOgProductCondition returns a boolean if a field has been set.
func (o *OgObject) HasOgProductCondition() bool {
	if o != nil && !IsNil(o.OgProductCondition) {
		return true
	}

	return false
}

// SetOgProductCondition gets a reference to the given string and assigns it to the OgProductCondition field.
func (o *OgObject) SetOgProductCondition(v string) {
	o.OgProductCondition = &v
}

// GetOgProductPriceAmount returns the OgProductPriceAmount field value if set, zero value otherwise.
func (o *OgObject) GetOgProductPriceAmount() string {
	if o == nil || IsNil(o.OgProductPriceAmount) {
		var ret string
		return ret
	}
	return *o.OgProductPriceAmount
}

// GetOgProductPriceAmountOk returns a tuple with the OgProductPriceAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgProductPriceAmountOk() (*string, bool) {
	if o == nil || IsNil(o.OgProductPriceAmount) {
		return nil, false
	}
	return o.OgProductPriceAmount, true
}

// HasOgProductPriceAmount returns a boolean if a field has been set.
func (o *OgObject) HasOgProductPriceAmount() bool {
	if o != nil && !IsNil(o.OgProductPriceAmount) {
		return true
	}

	return false
}

// SetOgProductPriceAmount gets a reference to the given string and assigns it to the OgProductPriceAmount field.
func (o *OgObject) SetOgProductPriceAmount(v string) {
	o.OgProductPriceAmount = &v
}

// GetOgProductPriceCurrency returns the OgProductPriceCurrency field value if set, zero value otherwise.
func (o *OgObject) GetOgProductPriceCurrency() string {
	if o == nil || IsNil(o.OgProductPriceCurrency) {
		var ret string
		return ret
	}
	return *o.OgProductPriceCurrency
}

// GetOgProductPriceCurrencyOk returns a tuple with the OgProductPriceCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgProductPriceCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.OgProductPriceCurrency) {
		return nil, false
	}
	return o.OgProductPriceCurrency, true
}

// HasOgProductPriceCurrency returns a boolean if a field has been set.
func (o *OgObject) HasOgProductPriceCurrency() bool {
	if o != nil && !IsNil(o.OgProductPriceCurrency) {
		return true
	}

	return false
}

// SetOgProductPriceCurrency gets a reference to the given string and assigns it to the OgProductPriceCurrency field.
func (o *OgObject) SetOgProductPriceCurrency(v string) {
	o.OgProductPriceCurrency = &v
}

// GetOgProductRetailerItemId returns the OgProductRetailerItemId field value if set, zero value otherwise.
func (o *OgObject) GetOgProductRetailerItemId() string {
	if o == nil || IsNil(o.OgProductRetailerItemId) {
		var ret string
		return ret
	}
	return *o.OgProductRetailerItemId
}

// GetOgProductRetailerItemIdOk returns a tuple with the OgProductRetailerItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgProductRetailerItemIdOk() (*string, bool) {
	if o == nil || IsNil(o.OgProductRetailerItemId) {
		return nil, false
	}
	return o.OgProductRetailerItemId, true
}

// HasOgProductRetailerItemId returns a boolean if a field has been set.
func (o *OgObject) HasOgProductRetailerItemId() bool {
	if o != nil && !IsNil(o.OgProductRetailerItemId) {
		return true
	}

	return false
}

// SetOgProductRetailerItemId gets a reference to the given string and assigns it to the OgProductRetailerItemId field.
func (o *OgObject) SetOgProductRetailerItemId(v string) {
	o.OgProductRetailerItemId = &v
}

// GetOgSiteName returns the OgSiteName field value if set, zero value otherwise.
func (o *OgObject) GetOgSiteName() string {
	if o == nil || IsNil(o.OgSiteName) {
		var ret string
		return ret
	}
	return *o.OgSiteName
}

// GetOgSiteNameOk returns a tuple with the OgSiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgSiteNameOk() (*string, bool) {
	if o == nil || IsNil(o.OgSiteName) {
		return nil, false
	}
	return o.OgSiteName, true
}

// HasOgSiteName returns a boolean if a field has been set.
func (o *OgObject) HasOgSiteName() bool {
	if o != nil && !IsNil(o.OgSiteName) {
		return true
	}

	return false
}

// SetOgSiteName gets a reference to the given string and assigns it to the OgSiteName field.
func (o *OgObject) SetOgSiteName(v string) {
	o.OgSiteName = &v
}

// GetOgTitle returns the OgTitle field value if set, zero value otherwise.
func (o *OgObject) GetOgTitle() string {
	if o == nil || IsNil(o.OgTitle) {
		var ret string
		return ret
	}
	return *o.OgTitle
}

// GetOgTitleOk returns a tuple with the OgTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgTitleOk() (*string, bool) {
	if o == nil || IsNil(o.OgTitle) {
		return nil, false
	}
	return o.OgTitle, true
}

// HasOgTitle returns a boolean if a field has been set.
func (o *OgObject) HasOgTitle() bool {
	if o != nil && !IsNil(o.OgTitle) {
		return true
	}

	return false
}

// SetOgTitle gets a reference to the given string and assigns it to the OgTitle field.
func (o *OgObject) SetOgTitle(v string) {
	o.OgTitle = &v
}

// GetOgType returns the OgType field value if set, zero value otherwise.
func (o *OgObject) GetOgType() string {
	if o == nil || IsNil(o.OgType) {
		var ret string
		return ret
	}
	return *o.OgType
}

// GetOgTypeOk returns a tuple with the OgType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OgType) {
		return nil, false
	}
	return o.OgType, true
}

// HasOgType returns a boolean if a field has been set.
func (o *OgObject) HasOgType() bool {
	if o != nil && !IsNil(o.OgType) {
		return true
	}

	return false
}

// SetOgType gets a reference to the given string and assigns it to the OgType field.
func (o *OgObject) SetOgType(v string) {
	o.OgType = &v
}

// GetOgUrl returns the OgUrl field value if set, zero value otherwise.
func (o *OgObject) GetOgUrl() string {
	if o == nil || IsNil(o.OgUrl) {
		var ret string
		return ret
	}
	return *o.OgUrl
}

// GetOgUrlOk returns a tuple with the OgUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OgUrl) {
		return nil, false
	}
	return o.OgUrl, true
}

// HasOgUrl returns a boolean if a field has been set.
func (o *OgObject) HasOgUrl() bool {
	if o != nil && !IsNil(o.OgUrl) {
		return true
	}

	return false
}

// SetOgUrl gets a reference to the given string and assigns it to the OgUrl field.
func (o *OgObject) SetOgUrl(v string) {
	o.OgUrl = &v
}

// GetOgVideo returns the OgVideo field value if set, zero value otherwise.
func (o *OgObject) GetOgVideo() []VideoObject {
	if o == nil || IsNil(o.OgVideo) {
		var ret []VideoObject
		return ret
	}
	return o.OgVideo
}

// GetOgVideoOk returns a tuple with the OgVideo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoOk() ([]VideoObject, bool) {
	if o == nil || IsNil(o.OgVideo) {
		return nil, false
	}
	return o.OgVideo, true
}

// HasOgVideo returns a boolean if a field has been set.
func (o *OgObject) HasOgVideo() bool {
	if o != nil && !IsNil(o.OgVideo) {
		return true
	}

	return false
}

// SetOgVideo gets a reference to the given []VideoObject and assigns it to the OgVideo field.
func (o *OgObject) SetOgVideo(v []VideoObject) {
	o.OgVideo = v
}

// GetOgVideoActor returns the OgVideoActor field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoActor() string {
	if o == nil || IsNil(o.OgVideoActor) {
		var ret string
		return ret
	}
	return *o.OgVideoActor
}

// GetOgVideoActorOk returns a tuple with the OgVideoActor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoActorOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoActor) {
		return nil, false
	}
	return o.OgVideoActor, true
}

// HasOgVideoActor returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoActor() bool {
	if o != nil && !IsNil(o.OgVideoActor) {
		return true
	}

	return false
}

// SetOgVideoActor gets a reference to the given string and assigns it to the OgVideoActor field.
func (o *OgObject) SetOgVideoActor(v string) {
	o.OgVideoActor = &v
}

// GetOgVideoActorId returns the OgVideoActorId field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoActorId() string {
	if o == nil || IsNil(o.OgVideoActorId) {
		var ret string
		return ret
	}
	return *o.OgVideoActorId
}

// GetOgVideoActorIdOk returns a tuple with the OgVideoActorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoActorIdOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoActorId) {
		return nil, false
	}
	return o.OgVideoActorId, true
}

// HasOgVideoActorId returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoActorId() bool {
	if o != nil && !IsNil(o.OgVideoActorId) {
		return true
	}

	return false
}

// SetOgVideoActorId gets a reference to the given string and assigns it to the OgVideoActorId field.
func (o *OgObject) SetOgVideoActorId(v string) {
	o.OgVideoActorId = &v
}

// GetOgVideoActorRole returns the OgVideoActorRole field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoActorRole() string {
	if o == nil || IsNil(o.OgVideoActorRole) {
		var ret string
		return ret
	}
	return *o.OgVideoActorRole
}

// GetOgVideoActorRoleOk returns a tuple with the OgVideoActorRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoActorRoleOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoActorRole) {
		return nil, false
	}
	return o.OgVideoActorRole, true
}

// HasOgVideoActorRole returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoActorRole() bool {
	if o != nil && !IsNil(o.OgVideoActorRole) {
		return true
	}

	return false
}

// SetOgVideoActorRole gets a reference to the given string and assigns it to the OgVideoActorRole field.
func (o *OgObject) SetOgVideoActorRole(v string) {
	o.OgVideoActorRole = &v
}

// GetOgVideoDirector returns the OgVideoDirector field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoDirector() string {
	if o == nil || IsNil(o.OgVideoDirector) {
		var ret string
		return ret
	}
	return *o.OgVideoDirector
}

// GetOgVideoDirectorOk returns a tuple with the OgVideoDirector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoDirectorOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoDirector) {
		return nil, false
	}
	return o.OgVideoDirector, true
}

// HasOgVideoDirector returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoDirector() bool {
	if o != nil && !IsNil(o.OgVideoDirector) {
		return true
	}

	return false
}

// SetOgVideoDirector gets a reference to the given string and assigns it to the OgVideoDirector field.
func (o *OgObject) SetOgVideoDirector(v string) {
	o.OgVideoDirector = &v
}

// GetOgVideoDuration returns the OgVideoDuration field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoDuration() string {
	if o == nil || IsNil(o.OgVideoDuration) {
		var ret string
		return ret
	}
	return *o.OgVideoDuration
}

// GetOgVideoDurationOk returns a tuple with the OgVideoDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoDurationOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoDuration) {
		return nil, false
	}
	return o.OgVideoDuration, true
}

// HasOgVideoDuration returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoDuration() bool {
	if o != nil && !IsNil(o.OgVideoDuration) {
		return true
	}

	return false
}

// SetOgVideoDuration gets a reference to the given string and assigns it to the OgVideoDuration field.
func (o *OgObject) SetOgVideoDuration(v string) {
	o.OgVideoDuration = &v
}

// GetOgVideoOther returns the OgVideoOther field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoOther() string {
	if o == nil || IsNil(o.OgVideoOther) {
		var ret string
		return ret
	}
	return *o.OgVideoOther
}

// GetOgVideoOtherOk returns a tuple with the OgVideoOther field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoOtherOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoOther) {
		return nil, false
	}
	return o.OgVideoOther, true
}

// HasOgVideoOther returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoOther() bool {
	if o != nil && !IsNil(o.OgVideoOther) {
		return true
	}

	return false
}

// SetOgVideoOther gets a reference to the given string and assigns it to the OgVideoOther field.
func (o *OgObject) SetOgVideoOther(v string) {
	o.OgVideoOther = &v
}

// GetOgVideoReleaseDate returns the OgVideoReleaseDate field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoReleaseDate() string {
	if o == nil || IsNil(o.OgVideoReleaseDate) {
		var ret string
		return ret
	}
	return *o.OgVideoReleaseDate
}

// GetOgVideoReleaseDateOk returns a tuple with the OgVideoReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoReleaseDateOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoReleaseDate) {
		return nil, false
	}
	return o.OgVideoReleaseDate, true
}

// HasOgVideoReleaseDate returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoReleaseDate() bool {
	if o != nil && !IsNil(o.OgVideoReleaseDate) {
		return true
	}

	return false
}

// SetOgVideoReleaseDate gets a reference to the given string and assigns it to the OgVideoReleaseDate field.
func (o *OgObject) SetOgVideoReleaseDate(v string) {
	o.OgVideoReleaseDate = &v
}

// GetOgVideoSecureURL returns the OgVideoSecureURL field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoSecureURL() string {
	if o == nil || IsNil(o.OgVideoSecureURL) {
		var ret string
		return ret
	}
	return *o.OgVideoSecureURL
}

// GetOgVideoSecureURLOk returns a tuple with the OgVideoSecureURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoSecureURLOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoSecureURL) {
		return nil, false
	}
	return o.OgVideoSecureURL, true
}

// HasOgVideoSecureURL returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoSecureURL() bool {
	if o != nil && !IsNil(o.OgVideoSecureURL) {
		return true
	}

	return false
}

// SetOgVideoSecureURL gets a reference to the given string and assigns it to the OgVideoSecureURL field.
func (o *OgObject) SetOgVideoSecureURL(v string) {
	o.OgVideoSecureURL = &v
}

// GetOgVideoSeries returns the OgVideoSeries field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoSeries() string {
	if o == nil || IsNil(o.OgVideoSeries) {
		var ret string
		return ret
	}
	return *o.OgVideoSeries
}

// GetOgVideoSeriesOk returns a tuple with the OgVideoSeries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoSeriesOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoSeries) {
		return nil, false
	}
	return o.OgVideoSeries, true
}

// HasOgVideoSeries returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoSeries() bool {
	if o != nil && !IsNil(o.OgVideoSeries) {
		return true
	}

	return false
}

// SetOgVideoSeries gets a reference to the given string and assigns it to the OgVideoSeries field.
func (o *OgObject) SetOgVideoSeries(v string) {
	o.OgVideoSeries = &v
}

// GetOgVideoTag returns the OgVideoTag field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoTag() string {
	if o == nil || IsNil(o.OgVideoTag) {
		var ret string
		return ret
	}
	return *o.OgVideoTag
}

// GetOgVideoTagOk returns a tuple with the OgVideoTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoTagOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoTag) {
		return nil, false
	}
	return o.OgVideoTag, true
}

// HasOgVideoTag returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoTag() bool {
	if o != nil && !IsNil(o.OgVideoTag) {
		return true
	}

	return false
}

// SetOgVideoTag gets a reference to the given string and assigns it to the OgVideoTag field.
func (o *OgObject) SetOgVideoTag(v string) {
	o.OgVideoTag = &v
}

// GetOgVideoTvShow returns the OgVideoTvShow field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoTvShow() string {
	if o == nil || IsNil(o.OgVideoTvShow) {
		var ret string
		return ret
	}
	return *o.OgVideoTvShow
}

// GetOgVideoTvShowOk returns a tuple with the OgVideoTvShow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoTvShowOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoTvShow) {
		return nil, false
	}
	return o.OgVideoTvShow, true
}

// HasOgVideoTvShow returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoTvShow() bool {
	if o != nil && !IsNil(o.OgVideoTvShow) {
		return true
	}

	return false
}

// SetOgVideoTvShow gets a reference to the given string and assigns it to the OgVideoTvShow field.
func (o *OgObject) SetOgVideoTvShow(v string) {
	o.OgVideoTvShow = &v
}

// GetOgVideoWriter returns the OgVideoWriter field value if set, zero value otherwise.
func (o *OgObject) GetOgVideoWriter() string {
	if o == nil || IsNil(o.OgVideoWriter) {
		var ret string
		return ret
	}
	return *o.OgVideoWriter
}

// GetOgVideoWriterOk returns a tuple with the OgVideoWriter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgVideoWriterOk() (*string, bool) {
	if o == nil || IsNil(o.OgVideoWriter) {
		return nil, false
	}
	return o.OgVideoWriter, true
}

// HasOgVideoWriter returns a boolean if a field has been set.
func (o *OgObject) HasOgVideoWriter() bool {
	if o != nil && !IsNil(o.OgVideoWriter) {
		return true
	}

	return false
}

// SetOgVideoWriter gets a reference to the given string and assigns it to the OgVideoWriter field.
func (o *OgObject) SetOgVideoWriter(v string) {
	o.OgVideoWriter = &v
}

// GetOgWebsite returns the OgWebsite field value if set, zero value otherwise.
func (o *OgObject) GetOgWebsite() string {
	if o == nil || IsNil(o.OgWebsite) {
		var ret string
		return ret
	}
	return *o.OgWebsite
}

// GetOgWebsiteOk returns a tuple with the OgWebsite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetOgWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.OgWebsite) {
		return nil, false
	}
	return o.OgWebsite, true
}

// HasOgWebsite returns a boolean if a field has been set.
func (o *OgObject) HasOgWebsite() bool {
	if o != nil && !IsNil(o.OgWebsite) {
		return true
	}

	return false
}

// SetOgWebsite gets a reference to the given string and assigns it to the OgWebsite field.
func (o *OgObject) SetOgWebsite(v string) {
	o.OgWebsite = &v
}

// GetUpdatedTime returns the UpdatedTime field value if set, zero value otherwise.
func (o *OgObject) GetUpdatedTime() string {
	if o == nil || IsNil(o.UpdatedTime) {
		var ret string
		return ret
	}
	return *o.UpdatedTime
}

// GetUpdatedTimeOk returns a tuple with the UpdatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OgObject) GetUpdatedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedTime) {
		return nil, false
	}
	return o.UpdatedTime, true
}

// HasUpdatedTime returns a boolean if a field has been set.
func (o *OgObject) HasUpdatedTime() bool {
	if o != nil && !IsNil(o.UpdatedTime) {
		return true
	}

	return false
}

// SetUpdatedTime gets a reference to the given string and assigns it to the UpdatedTime field.
func (o *OgObject) SetUpdatedTime(v string) {
	o.UpdatedTime = &v
}

func (o OgObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OgObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Favicon) {
		toSerialize["favicon"] = o.Favicon
	}
	if !IsNil(o.ModifiedTime) {
		toSerialize["modifiedTime"] = o.ModifiedTime
	}
	if !IsNil(o.OgArticleAuthor) {
		toSerialize["ogArticleAuthor"] = o.OgArticleAuthor
	}
	if !IsNil(o.OgArticleExpirationTime) {
		toSerialize["ogArticleExpirationTime"] = o.OgArticleExpirationTime
	}
	if !IsNil(o.OgArticleModifiedTime) {
		toSerialize["ogArticleModifiedTime"] = o.OgArticleModifiedTime
	}
	if !IsNil(o.OgArticlePublishedTime) {
		toSerialize["ogArticlePublishedTime"] = o.OgArticlePublishedTime
	}
	if !IsNil(o.OgArticlePublisher) {
		toSerialize["ogArticlePublisher"] = o.OgArticlePublisher
	}
	if !IsNil(o.OgArticleSection) {
		toSerialize["ogArticleSection"] = o.OgArticleSection
	}
	if !IsNil(o.OgArticleTag) {
		toSerialize["ogArticleTag"] = o.OgArticleTag
	}
	if !IsNil(o.OgAudio) {
		toSerialize["ogAudio"] = o.OgAudio
	}
	if !IsNil(o.OgAudioSecureURL) {
		toSerialize["ogAudioSecureURL"] = o.OgAudioSecureURL
	}
	if !IsNil(o.OgAudioType) {
		toSerialize["ogAudioType"] = o.OgAudioType
	}
	if !IsNil(o.OgAudioURL) {
		toSerialize["ogAudioURL"] = o.OgAudioURL
	}
	if !IsNil(o.OgAvailability) {
		toSerialize["ogAvailability"] = o.OgAvailability
	}
	if !IsNil(o.OgDate) {
		toSerialize["ogDate"] = o.OgDate
	}
	if !IsNil(o.OgDescription) {
		toSerialize["ogDescription"] = o.OgDescription
	}
	if !IsNil(o.OgDeterminer) {
		toSerialize["ogDeterminer"] = o.OgDeterminer
	}
	if !IsNil(o.OgEpisode) {
		toSerialize["ogEpisode"] = o.OgEpisode
	}
	if !IsNil(o.OgImage) {
		toSerialize["ogImage"] = o.OgImage
	}
	if !IsNil(o.OgLocale) {
		toSerialize["ogLocale"] = o.OgLocale
	}
	if !IsNil(o.OgLocaleAlternate) {
		toSerialize["ogLocaleAlternate"] = o.OgLocaleAlternate
	}
	if !IsNil(o.OgLogo) {
		toSerialize["ogLogo"] = o.OgLogo
	}
	if !IsNil(o.OgMovie) {
		toSerialize["ogMovie"] = o.OgMovie
	}
	if !IsNil(o.OgPriceAmount) {
		toSerialize["ogPriceAmount"] = o.OgPriceAmount
	}
	if !IsNil(o.OgPriceCurrency) {
		toSerialize["ogPriceCurrency"] = o.OgPriceCurrency
	}
	if !IsNil(o.OgProductAvailability) {
		toSerialize["ogProductAvailability"] = o.OgProductAvailability
	}
	if !IsNil(o.OgProductCondition) {
		toSerialize["ogProductCondition"] = o.OgProductCondition
	}
	if !IsNil(o.OgProductPriceAmount) {
		toSerialize["ogProductPriceAmount"] = o.OgProductPriceAmount
	}
	if !IsNil(o.OgProductPriceCurrency) {
		toSerialize["ogProductPriceCurrency"] = o.OgProductPriceCurrency
	}
	if !IsNil(o.OgProductRetailerItemId) {
		toSerialize["ogProductRetailerItemId"] = o.OgProductRetailerItemId
	}
	if !IsNil(o.OgSiteName) {
		toSerialize["ogSiteName"] = o.OgSiteName
	}
	if !IsNil(o.OgTitle) {
		toSerialize["ogTitle"] = o.OgTitle
	}
	if !IsNil(o.OgType) {
		toSerialize["ogType"] = o.OgType
	}
	if !IsNil(o.OgUrl) {
		toSerialize["ogUrl"] = o.OgUrl
	}
	if !IsNil(o.OgVideo) {
		toSerialize["ogVideo"] = o.OgVideo
	}
	if !IsNil(o.OgVideoActor) {
		toSerialize["ogVideoActor"] = o.OgVideoActor
	}
	if !IsNil(o.OgVideoActorId) {
		toSerialize["ogVideoActorId"] = o.OgVideoActorId
	}
	if !IsNil(o.OgVideoActorRole) {
		toSerialize["ogVideoActorRole"] = o.OgVideoActorRole
	}
	if !IsNil(o.OgVideoDirector) {
		toSerialize["ogVideoDirector"] = o.OgVideoDirector
	}
	if !IsNil(o.OgVideoDuration) {
		toSerialize["ogVideoDuration"] = o.OgVideoDuration
	}
	if !IsNil(o.OgVideoOther) {
		toSerialize["ogVideoOther"] = o.OgVideoOther
	}
	if !IsNil(o.OgVideoReleaseDate) {
		toSerialize["ogVideoReleaseDate"] = o.OgVideoReleaseDate
	}
	if !IsNil(o.OgVideoSecureURL) {
		toSerialize["ogVideoSecureURL"] = o.OgVideoSecureURL
	}
	if !IsNil(o.OgVideoSeries) {
		toSerialize["ogVideoSeries"] = o.OgVideoSeries
	}
	if !IsNil(o.OgVideoTag) {
		toSerialize["ogVideoTag"] = o.OgVideoTag
	}
	if !IsNil(o.OgVideoTvShow) {
		toSerialize["ogVideoTvShow"] = o.OgVideoTvShow
	}
	if !IsNil(o.OgVideoWriter) {
		toSerialize["ogVideoWriter"] = o.OgVideoWriter
	}
	if !IsNil(o.OgWebsite) {
		toSerialize["ogWebsite"] = o.OgWebsite
	}
	if !IsNil(o.UpdatedTime) {
		toSerialize["updatedTime"] = o.UpdatedTime
	}
	return toSerialize, nil
}

type NullableOgObject struct {
	value *OgObject
	isSet bool
}

func (v NullableOgObject) Get() *OgObject {
	return v.value
}

func (v *NullableOgObject) Set(val *OgObject) {
	v.value = val
	v.isSet = true
}

func (v NullableOgObject) IsSet() bool {
	return v.isSet
}

func (v *NullableOgObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOgObject(val *OgObject) *NullableOgObject {
	return &NullableOgObject{value: val, isSet: true}
}

func (v NullableOgObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOgObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


