/*
Farcaster Hub API

Testing StorageAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hub

import (
	"context"
	openapiclient "github.com/neynarxyz/go-sdk/hub"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_hub_StorageAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StorageAPIService LookupUserStorageLimit", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.StorageAPI.LookupUserStorageLimit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
