/*
Farcaster Hub API

Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 

API version: 2.21.0
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReactionBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReactionBody{}

// ReactionBody Specifies the details of a reaction to content on Farcaster. A reaction must specify its type (like/recast) and either a target cast ID or URL to react to. Only one target (either castId or URL) should be specified per reaction.
type ReactionBody struct {
	Type ReactionType `json:"type"`
	// The unique identifier of the cast being reacted to. Must be a valid CastId containing the creator's FID and the cast's hash.
	TargetCastId *CastId `json:"targetCastId,omitempty"`
	// The URL being reacted to. Used when reacting to external content or when the cast ID is not available.
	TargetUrl *string `json:"targetUrl,omitempty"`
}

type _ReactionBody ReactionBody

// NewReactionBody instantiates a new ReactionBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReactionBody(type_ ReactionType) *ReactionBody {
	this := ReactionBody{}
	this.Type = type_
	return &this
}

// NewReactionBodyWithDefaults instantiates a new ReactionBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReactionBodyWithDefaults() *ReactionBody {
	this := ReactionBody{}
	var type_ ReactionType = LIKE
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *ReactionBody) GetType() ReactionType {
	if o == nil {
		var ret ReactionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReactionBody) GetTypeOk() (*ReactionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReactionBody) SetType(v ReactionType) {
	o.Type = v
}

// GetTargetCastId returns the TargetCastId field value if set, zero value otherwise.
func (o *ReactionBody) GetTargetCastId() CastId {
	if o == nil || IsNil(o.TargetCastId) {
		var ret CastId
		return ret
	}
	return *o.TargetCastId
}

// GetTargetCastIdOk returns a tuple with the TargetCastId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactionBody) GetTargetCastIdOk() (*CastId, bool) {
	if o == nil || IsNil(o.TargetCastId) {
		return nil, false
	}
	return o.TargetCastId, true
}

// HasTargetCastId returns a boolean if a field has been set.
func (o *ReactionBody) HasTargetCastId() bool {
	if o != nil && !IsNil(o.TargetCastId) {
		return true
	}

	return false
}

// SetTargetCastId gets a reference to the given CastId and assigns it to the TargetCastId field.
func (o *ReactionBody) SetTargetCastId(v CastId) {
	o.TargetCastId = &v
}

// GetTargetUrl returns the TargetUrl field value if set, zero value otherwise.
func (o *ReactionBody) GetTargetUrl() string {
	if o == nil || IsNil(o.TargetUrl) {
		var ret string
		return ret
	}
	return *o.TargetUrl
}

// GetTargetUrlOk returns a tuple with the TargetUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactionBody) GetTargetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.TargetUrl) {
		return nil, false
	}
	return o.TargetUrl, true
}

// HasTargetUrl returns a boolean if a field has been set.
func (o *ReactionBody) HasTargetUrl() bool {
	if o != nil && !IsNil(o.TargetUrl) {
		return true
	}

	return false
}

// SetTargetUrl gets a reference to the given string and assigns it to the TargetUrl field.
func (o *ReactionBody) SetTargetUrl(v string) {
	o.TargetUrl = &v
}

func (o ReactionBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReactionBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.TargetCastId) {
		toSerialize["targetCastId"] = o.TargetCastId
	}
	if !IsNil(o.TargetUrl) {
		toSerialize["targetUrl"] = o.TargetUrl
	}
	return toSerialize, nil
}

func (o *ReactionBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReactionBody := _ReactionBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReactionBody)

	if err != nil {
		return err
	}

	*o = ReactionBody(varReactionBody)

	return err
}

type NullableReactionBody struct {
	value *ReactionBody
	isSet bool
}

func (v NullableReactionBody) Get() *ReactionBody {
	return v.value
}

func (v *NullableReactionBody) Set(val *ReactionBody) {
	v.value = val
	v.isSet = true
}

func (v NullableReactionBody) IsSet() bool {
	return v.isSet
}

func (v *NullableReactionBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReactionBody(val *ReactionBody) *NullableReactionBody {
	return &NullableReactionBody{value: val, isSet: true}
}

func (v NullableReactionBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReactionBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


