/*
Farcaster Hub API

Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 

API version: 2.21.0
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hub

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FetchCastReactions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchCastReactions200Response{}

// FetchCastReactions200Response struct for FetchCastReactions200Response
type FetchCastReactions200Response struct {
	// Base64-encoded pagination token for fetching the next page of results. An empty value indicates there are no more pages to return. Used in conjunction with the pageSize parameter to implement pagination across large result sets.
	NextPageToken string `json:"nextPageToken" validate:"regexp=^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$"`
	Messages []Reaction `json:"messages"`
}

type _FetchCastReactions200Response FetchCastReactions200Response

// NewFetchCastReactions200Response instantiates a new FetchCastReactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchCastReactions200Response(nextPageToken string, messages []Reaction) *FetchCastReactions200Response {
	this := FetchCastReactions200Response{}
	this.NextPageToken = nextPageToken
	this.Messages = messages
	return &this
}

// NewFetchCastReactions200ResponseWithDefaults instantiates a new FetchCastReactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchCastReactions200ResponseWithDefaults() *FetchCastReactions200Response {
	this := FetchCastReactions200Response{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value
func (o *FetchCastReactions200Response) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *FetchCastReactions200Response) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *FetchCastReactions200Response) SetNextPageToken(v string) {
	o.NextPageToken = v
}

// GetMessages returns the Messages field value
func (o *FetchCastReactions200Response) GetMessages() []Reaction {
	if o == nil {
		var ret []Reaction
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *FetchCastReactions200Response) GetMessagesOk() ([]Reaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *FetchCastReactions200Response) SetMessages(v []Reaction) {
	o.Messages = v
}

func (o FetchCastReactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchCastReactions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nextPageToken"] = o.NextPageToken
	toSerialize["messages"] = o.Messages
	return toSerialize, nil
}

func (o *FetchCastReactions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nextPageToken",
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFetchCastReactions200Response := _FetchCastReactions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFetchCastReactions200Response)

	if err != nil {
		return err
	}

	*o = FetchCastReactions200Response(varFetchCastReactions200Response)

	return err
}

type NullableFetchCastReactions200Response struct {
	value *FetchCastReactions200Response
	isSet bool
}

func (v NullableFetchCastReactions200Response) Get() *FetchCastReactions200Response {
	return v.value
}

func (v *NullableFetchCastReactions200Response) Set(val *FetchCastReactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchCastReactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchCastReactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchCastReactions200Response(val *FetchCastReactions200Response) *NullableFetchCastReactions200Response {
	return &NullableFetchCastReactions200Response{value: val, isSet: true}
}

func (v NullableFetchCastReactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchCastReactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


