/*
Farcaster API V2

The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details.

API version: 2.33.1
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CastEmbeddedChannel - struct for CastEmbeddedChannel
type CastEmbeddedChannel struct {
	ChannelDehydrated *ChannelDehydrated
	Any               *interface{}
}

// ChannelDehydratedAsCastEmbeddedChannel is a convenience function that returns ChannelDehydrated wrapped in CastEmbeddedChannel
func ChannelDehydratedAsCastEmbeddedChannel(v *ChannelDehydrated) CastEmbeddedChannel {
	return CastEmbeddedChannel{
		ChannelDehydrated: v,
	}
}

// interface{}AsCastEmbeddedChannel is a convenience function that returns interface{} wrapped in CastEmbeddedChannel
func AnyAsCastEmbeddedChannel(v *interface{}) CastEmbeddedChannel {
	return CastEmbeddedChannel{
		Any: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CastEmbeddedChannel) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ChannelDehydrated
	err = newStrictDecoder(data).Decode(&dst.ChannelDehydrated)
	if err == nil {
		jsonChannelDehydrated, _ := json.Marshal(dst.ChannelDehydrated)
		if string(jsonChannelDehydrated) == "{}" { // empty struct
			dst.ChannelDehydrated = nil
		} else {
			if err = validator.Validate(dst.ChannelDehydrated); err != nil {
				dst.ChannelDehydrated = nil
			} else {
				match++
			}
		}
	} else {
		dst.ChannelDehydrated = nil
	}

	// try to unmarshal data into Any
	err = newStrictDecoder(data).Decode(&dst.Any)
	if err == nil {
		jsonAny, _ := json.Marshal(dst.Any)
		if string(jsonAny) == "{}" { // empty struct
			dst.Any = nil
		} else {
			if err = validator.Validate(dst.Any); err != nil {
				dst.Any = nil
			} else {
				match++
			}
		}
	} else {
		dst.Any = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ChannelDehydrated = nil
		dst.Any = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CastEmbeddedChannel)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CastEmbeddedChannel)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CastEmbeddedChannel) MarshalJSON() ([]byte, error) {
	if src.ChannelDehydrated != nil {
		return json.Marshal(&src.ChannelDehydrated)
	}

	if src.Any != nil {
		return json.Marshal(&src.Any)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CastEmbeddedChannel) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ChannelDehydrated != nil {
		return obj.ChannelDehydrated
	}

	if obj.Any != nil {
		return obj.Any
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CastEmbeddedChannel) GetActualInstanceValue() interface{} {
	if obj.ChannelDehydrated != nil {
		return *obj.ChannelDehydrated
	}

	if obj.Any != nil {
		return *obj.Any
	}

	// all schemas are nil
	return nil
}

type NullableCastEmbeddedChannel struct {
	value *CastEmbeddedChannel
	isSet bool
}

func (v NullableCastEmbeddedChannel) Get() *CastEmbeddedChannel {
	return v.value
}

func (v *NullableCastEmbeddedChannel) Set(val *CastEmbeddedChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableCastEmbeddedChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableCastEmbeddedChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCastEmbeddedChannel(val *CastEmbeddedChannel) *NullableCastEmbeddedChannel {
	return &NullableCastEmbeddedChannel{value: val, isSet: true}
}

func (v NullableCastEmbeddedChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCastEmbeddedChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
