/*
Farcaster API V2

The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details.

API version: 2.33.1
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CastParentAuthorFid - struct for CastParentAuthorFid
type CastParentAuthorFid struct {
	Int32 *int32
	Any   *interface{}
}

// int32AsCastParentAuthorFid is a convenience function that returns int32 wrapped in CastParentAuthorFid
func Int32AsCastParentAuthorFid(v *int32) CastParentAuthorFid {
	return CastParentAuthorFid{
		Int32: v,
	}
}

// interface{}AsCastParentAuthorFid is a convenience function that returns interface{} wrapped in CastParentAuthorFid
func AnyAsCastParentAuthorFid(v *interface{}) CastParentAuthorFid {
	return CastParentAuthorFid{
		Any: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CastParentAuthorFid) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into Any
	err = newStrictDecoder(data).Decode(&dst.Any)
	if err == nil {
		jsonAny, _ := json.Marshal(dst.Any)
		if string(jsonAny) == "{}" { // empty struct
			dst.Any = nil
		} else {
			if err = validator.Validate(dst.Any); err != nil {
				dst.Any = nil
			} else {
				match++
			}
		}
	} else {
		dst.Any = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.Any = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CastParentAuthorFid)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CastParentAuthorFid)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CastParentAuthorFid) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.Any != nil {
		return json.Marshal(&src.Any)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CastParentAuthorFid) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.Any != nil {
		return obj.Any
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CastParentAuthorFid) GetActualInstanceValue() interface{} {
	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.Any != nil {
		return *obj.Any
	}

	// all schemas are nil
	return nil
}

type NullableCastParentAuthorFid struct {
	value *CastParentAuthorFid
	isSet bool
}

func (v NullableCastParentAuthorFid) Get() *CastParentAuthorFid {
	return v.value
}

func (v *NullableCastParentAuthorFid) Set(val *CastParentAuthorFid) {
	v.value = val
	v.isSet = true
}

func (v NullableCastParentAuthorFid) IsSet() bool {
	return v.isSet
}

func (v *NullableCastParentAuthorFid) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCastParentAuthorFid(val *CastParentAuthorFid) *NullableCastParentAuthorFid {
	return &NullableCastParentAuthorFid{value: val, isSet: true}
}

func (v NullableCastParentAuthorFid) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCastParentAuthorFid) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
