/*
Farcaster API V2

The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details.

API version: 2.33.1
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CastApp - struct for CastApp
type CastApp struct {
	UserDehydrated *UserDehydrated
	Any            *interface{}
}

// UserDehydratedAsCastApp is a convenience function that returns UserDehydrated wrapped in CastApp
func UserDehydratedAsCastApp(v *UserDehydrated) CastApp {
	return CastApp{
		UserDehydrated: v,
	}
}

// interface{}AsCastApp is a convenience function that returns interface{} wrapped in CastApp
func AnyAsCastApp(v *interface{}) CastApp {
	return CastApp{
		Any: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CastApp) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UserDehydrated
	err = newStrictDecoder(data).Decode(&dst.UserDehydrated)
	if err == nil {
		jsonUserDehydrated, _ := json.Marshal(dst.UserDehydrated)
		if string(jsonUserDehydrated) == "{}" { // empty struct
			dst.UserDehydrated = nil
		} else {
			if err = validator.Validate(dst.UserDehydrated); err != nil {
				dst.UserDehydrated = nil
			} else {
				match++
			}
		}
	} else {
		dst.UserDehydrated = nil
	}

	// try to unmarshal data into Any
	err = newStrictDecoder(data).Decode(&dst.Any)
	if err == nil {
		jsonAny, _ := json.Marshal(dst.Any)
		if string(jsonAny) == "{}" { // empty struct
			dst.Any = nil
		} else {
			if err = validator.Validate(dst.Any); err != nil {
				dst.Any = nil
			} else {
				match++
			}
		}
	} else {
		dst.Any = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UserDehydrated = nil
		dst.Any = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CastApp)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CastApp)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CastApp) MarshalJSON() ([]byte, error) {
	if src.UserDehydrated != nil {
		return json.Marshal(&src.UserDehydrated)
	}

	if src.Any != nil {
		return json.Marshal(&src.Any)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CastApp) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.UserDehydrated != nil {
		return obj.UserDehydrated
	}

	if obj.Any != nil {
		return obj.Any
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CastApp) GetActualInstanceValue() interface{} {
	if obj.UserDehydrated != nil {
		return *obj.UserDehydrated
	}

	if obj.Any != nil {
		return *obj.Any
	}

	// all schemas are nil
	return nil
}

type NullableCastApp struct {
	value *CastApp
	isSet bool
}

func (v NullableCastApp) Get() *CastApp {
	return v.value
}

func (v *NullableCastApp) Set(val *CastApp) {
	v.value = val
	v.isSet = true
}

func (v NullableCastApp) IsSet() bool {
	return v.isSet
}

func (v *NullableCastApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCastApp(val *CastApp) *NullableCastApp {
	return &NullableCastApp{value: val, isSet: true}
}

func (v NullableCastApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCastApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
