/*
Farcaster API V2

The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details. 

API version: 2.33.1
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OembedLinkData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OembedLinkData{}

// OembedLinkData struct for OembedLinkData
type OembedLinkData struct {
	Type string `json:"type"`
	Version string `json:"version"`
	// A text title, describing the resource.
	Title *string `json:"title,omitempty"`
	// The name of the author/owner of the resource.
	AuthorName *string `json:"author_name,omitempty"`
	// A URL for the author/owner of the resource.
	AuthorUrl *string `json:"author_url,omitempty"`
	// The name of the resource provider.
	ProviderName *string `json:"provider_name,omitempty"`
	// The url of the resource provider.
	ProviderUrl *string `json:"provider_url,omitempty"`
	// The suggested cache lifetime for this resource, in seconds. Consumers may choose to use this value or not.
	CacheAge *string `json:"cache_age,omitempty"`
	// A URL to a thumbnail image representing the resource. The thumbnail must respect any maxwidth and maxheight parameters. If this parameter is present, thumbnail_width and thumbnail_height must also be present.
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
	// The width of the optional thumbnail. If this parameter is present, thumbnail_url and thumbnail_height must also be present.
	ThumbnailWidth *float32 `json:"thumbnail_width,omitempty"`
	// The height of the optional thumbnail. If this parameter is present, thumbnail_url and thumbnail_width must also be present.
	ThumbnailHeight *float32 `json:"thumbnail_height,omitempty"`
}

type _OembedLinkData OembedLinkData

// NewOembedLinkData instantiates a new OembedLinkData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOembedLinkData(type_ string, version string) *OembedLinkData {
	this := OembedLinkData{}
	this.Type = type_
	this.Version = version
	return &this
}

// NewOembedLinkDataWithDefaults instantiates a new OembedLinkData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOembedLinkDataWithDefaults() *OembedLinkData {
	this := OembedLinkData{}
	return &this
}

// GetType returns the Type field value
func (o *OembedLinkData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OembedLinkData) SetType(v string) {
	o.Type = v
}


// GetVersion returns the Version field value
func (o *OembedLinkData) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *OembedLinkData) SetVersion(v string) {
	o.Version = v
}


// GetTitle returns the Title field value if set, zero value otherwise.
func (o *OembedLinkData) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *OembedLinkData) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *OembedLinkData) SetTitle(v string) {
	o.Title = &v
}

// GetAuthorName returns the AuthorName field value if set, zero value otherwise.
func (o *OembedLinkData) GetAuthorName() string {
	if o == nil || IsNil(o.AuthorName) {
		var ret string
		return ret
	}
	return *o.AuthorName
}

// GetAuthorNameOk returns a tuple with the AuthorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetAuthorNameOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorName) {
		return nil, false
	}
	return o.AuthorName, true
}

// HasAuthorName returns a boolean if a field has been set.
func (o *OembedLinkData) HasAuthorName() bool {
	if o != nil && !IsNil(o.AuthorName) {
		return true
	}

	return false
}

// SetAuthorName gets a reference to the given string and assigns it to the AuthorName field.
func (o *OembedLinkData) SetAuthorName(v string) {
	o.AuthorName = &v
}

// GetAuthorUrl returns the AuthorUrl field value if set, zero value otherwise.
func (o *OembedLinkData) GetAuthorUrl() string {
	if o == nil || IsNil(o.AuthorUrl) {
		var ret string
		return ret
	}
	return *o.AuthorUrl
}

// GetAuthorUrlOk returns a tuple with the AuthorUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetAuthorUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorUrl) {
		return nil, false
	}
	return o.AuthorUrl, true
}

// HasAuthorUrl returns a boolean if a field has been set.
func (o *OembedLinkData) HasAuthorUrl() bool {
	if o != nil && !IsNil(o.AuthorUrl) {
		return true
	}

	return false
}

// SetAuthorUrl gets a reference to the given string and assigns it to the AuthorUrl field.
func (o *OembedLinkData) SetAuthorUrl(v string) {
	o.AuthorUrl = &v
}

// GetProviderName returns the ProviderName field value if set, zero value otherwise.
func (o *OembedLinkData) GetProviderName() string {
	if o == nil || IsNil(o.ProviderName) {
		var ret string
		return ret
	}
	return *o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetProviderNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderName) {
		return nil, false
	}
	return o.ProviderName, true
}

// HasProviderName returns a boolean if a field has been set.
func (o *OembedLinkData) HasProviderName() bool {
	if o != nil && !IsNil(o.ProviderName) {
		return true
	}

	return false
}

// SetProviderName gets a reference to the given string and assigns it to the ProviderName field.
func (o *OembedLinkData) SetProviderName(v string) {
	o.ProviderName = &v
}

// GetProviderUrl returns the ProviderUrl field value if set, zero value otherwise.
func (o *OembedLinkData) GetProviderUrl() string {
	if o == nil || IsNil(o.ProviderUrl) {
		var ret string
		return ret
	}
	return *o.ProviderUrl
}

// GetProviderUrlOk returns a tuple with the ProviderUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetProviderUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderUrl) {
		return nil, false
	}
	return o.ProviderUrl, true
}

// HasProviderUrl returns a boolean if a field has been set.
func (o *OembedLinkData) HasProviderUrl() bool {
	if o != nil && !IsNil(o.ProviderUrl) {
		return true
	}

	return false
}

// SetProviderUrl gets a reference to the given string and assigns it to the ProviderUrl field.
func (o *OembedLinkData) SetProviderUrl(v string) {
	o.ProviderUrl = &v
}

// GetCacheAge returns the CacheAge field value if set, zero value otherwise.
func (o *OembedLinkData) GetCacheAge() string {
	if o == nil || IsNil(o.CacheAge) {
		var ret string
		return ret
	}
	return *o.CacheAge
}

// GetCacheAgeOk returns a tuple with the CacheAge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetCacheAgeOk() (*string, bool) {
	if o == nil || IsNil(o.CacheAge) {
		return nil, false
	}
	return o.CacheAge, true
}

// HasCacheAge returns a boolean if a field has been set.
func (o *OembedLinkData) HasCacheAge() bool {
	if o != nil && !IsNil(o.CacheAge) {
		return true
	}

	return false
}

// SetCacheAge gets a reference to the given string and assigns it to the CacheAge field.
func (o *OembedLinkData) SetCacheAge(v string) {
	o.CacheAge = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *OembedLinkData) GetThumbnailUrl() string {
	if o == nil || IsNil(o.ThumbnailUrl) {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ThumbnailUrl) {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *OembedLinkData) HasThumbnailUrl() bool {
	if o != nil && !IsNil(o.ThumbnailUrl) {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *OembedLinkData) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

// GetThumbnailWidth returns the ThumbnailWidth field value if set, zero value otherwise.
func (o *OembedLinkData) GetThumbnailWidth() float32 {
	if o == nil || IsNil(o.ThumbnailWidth) {
		var ret float32
		return ret
	}
	return *o.ThumbnailWidth
}

// GetThumbnailWidthOk returns a tuple with the ThumbnailWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetThumbnailWidthOk() (*float32, bool) {
	if o == nil || IsNil(o.ThumbnailWidth) {
		return nil, false
	}
	return o.ThumbnailWidth, true
}

// HasThumbnailWidth returns a boolean if a field has been set.
func (o *OembedLinkData) HasThumbnailWidth() bool {
	if o != nil && !IsNil(o.ThumbnailWidth) {
		return true
	}

	return false
}

// SetThumbnailWidth gets a reference to the given float32 and assigns it to the ThumbnailWidth field.
func (o *OembedLinkData) SetThumbnailWidth(v float32) {
	o.ThumbnailWidth = &v
}

// GetThumbnailHeight returns the ThumbnailHeight field value if set, zero value otherwise.
func (o *OembedLinkData) GetThumbnailHeight() float32 {
	if o == nil || IsNil(o.ThumbnailHeight) {
		var ret float32
		return ret
	}
	return *o.ThumbnailHeight
}

// GetThumbnailHeightOk returns a tuple with the ThumbnailHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OembedLinkData) GetThumbnailHeightOk() (*float32, bool) {
	if o == nil || IsNil(o.ThumbnailHeight) {
		return nil, false
	}
	return o.ThumbnailHeight, true
}

// HasThumbnailHeight returns a boolean if a field has been set.
func (o *OembedLinkData) HasThumbnailHeight() bool {
	if o != nil && !IsNil(o.ThumbnailHeight) {
		return true
	}

	return false
}

// SetThumbnailHeight gets a reference to the given float32 and assigns it to the ThumbnailHeight field.
func (o *OembedLinkData) SetThumbnailHeight(v float32) {
	o.ThumbnailHeight = &v
}

func (o OembedLinkData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OembedLinkData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["version"] = o.Version
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.AuthorName) {
		toSerialize["author_name"] = o.AuthorName
	}
	if !IsNil(o.AuthorUrl) {
		toSerialize["author_url"] = o.AuthorUrl
	}
	if !IsNil(o.ProviderName) {
		toSerialize["provider_name"] = o.ProviderName
	}
	if !IsNil(o.ProviderUrl) {
		toSerialize["provider_url"] = o.ProviderUrl
	}
	if !IsNil(o.CacheAge) {
		toSerialize["cache_age"] = o.CacheAge
	}
	if !IsNil(o.ThumbnailUrl) {
		toSerialize["thumbnail_url"] = o.ThumbnailUrl
	}
	if !IsNil(o.ThumbnailWidth) {
		toSerialize["thumbnail_width"] = o.ThumbnailWidth
	}
	if !IsNil(o.ThumbnailHeight) {
		toSerialize["thumbnail_height"] = o.ThumbnailHeight
	}
	return toSerialize, nil
}

func (o *OembedLinkData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"version",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{} {
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == ""{
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil{
			return err
		}
	}
	varOembedLinkData := _OembedLinkData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOembedLinkData)

	if err != nil {
		return err
	}

	*o = OembedLinkData(varOembedLinkData)

	return err
}

type NullableOembedLinkData struct {
	value *OembedLinkData
	isSet bool
}

func (v NullableOembedLinkData) Get() *OembedLinkData {
	return v.value
}

func (v *NullableOembedLinkData) Set(val *OembedLinkData) {
	v.value = val
	v.isSet = true
}

func (v NullableOembedLinkData) IsSet() bool {
	return v.isSet
}

func (v *NullableOembedLinkData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOembedLinkData(val *OembedLinkData) *NullableOembedLinkData {
	return &NullableOembedLinkData{value: val, isSet: true}
}

func (v NullableOembedLinkData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOembedLinkData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


