/*
Farcaster API V2

The Farcaster API allows you to interact with the Farcaster protocol. See the [Neynar docs](https://docs.neynar.com/reference) for more details.

API version: 2.33.1
Contact: team@neynar.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SubscriptionCheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionCheckResponse{}

// SubscriptionCheckResponse struct for SubscriptionCheckResponse
type SubscriptionCheckResponse struct {
	AdditionalProperties map[string]interface{}
}

type _SubscriptionCheckResponse SubscriptionCheckResponse

// NewSubscriptionCheckResponse instantiates a new SubscriptionCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionCheckResponse() *SubscriptionCheckResponse {
	this := SubscriptionCheckResponse{}
	return &this
}

// NewSubscriptionCheckResponseWithDefaults instantiates a new SubscriptionCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionCheckResponseWithDefaults() *SubscriptionCheckResponse {
	this := SubscriptionCheckResponse{}
	return &this
}

func (o SubscriptionCheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionCheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubscriptionCheckResponse) UnmarshalJSON(data []byte) (err error) {
	varSubscriptionCheckResponse := _SubscriptionCheckResponse{}

	err = json.Unmarshal(data, &varSubscriptionCheckResponse)

	if err != nil {
		return err
	}

	*o = SubscriptionCheckResponse(varSubscriptionCheckResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubscriptionCheckResponse struct {
	value SubscriptionCheckResponse
	isSet bool
}

func (v NullableSubscriptionCheckResponse) Get() SubscriptionCheckResponse {
	return v.value
}

func (v *NullableSubscriptionCheckResponse) Set(val SubscriptionCheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionCheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionCheckResponse(val SubscriptionCheckResponse) *NullableSubscriptionCheckResponse {
	return &NullableSubscriptionCheckResponse{value: val, isSet: true}
}

func (v NullableSubscriptionCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
