name: Publish API and Hub API

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Build API
        run: |
          cd generated/api
          go build

      - name: Build Hub API
        run: |
          cd generated/hub-api
          go build

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Create and Push Tag
        run: |
          # Parse version from openapi.yaml using yq
          VERSION=$(yq '.info.version' generated/api/api/openapi.yaml)
          if [ -z "$VERSION" ]; then
            echo "Could not determine version from openapi.yaml"
            exit 1
          fi
          TAG_NAME="v$VERSION"
          # Only create tag if it doesn't already exist
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping."
            exit 0
          fi
          git tag $TAG_NAME
          git push origin $TAG_NAME